### ISSUE TITLE
index.html not displaying anything on Edge or Crome browser

### ISSUE THREAD

**Issue by JasmaB** [RodrigoSC/dndTree#4]
@RodrigoSC ,

I downloaded the dndtree-master.zip, uncompressed it and double clicked on index.html. 
Please find attached snapshot of index.html. Nothing is getting displayed. Kindly help. 

![image](https://cloud.githubusercontent.com/assets/15938574/15983537/58f7fc96-2fc8-11e6-9ff2-198f45dca217.png)

**Comment by RodrigoSC** [comment]
Hello Jasma,

Double clicking index.html does not work... you'll need to use a web server. Here are a couple of options for you:

1) If you're running IIS, just copy the folder of the project somewhere to your IIS root folder (c:\inetpub, or something like that... I'm on a mac, so I'm not sure)
2) If you have python installed, you can run the following command on your project folder: python -m SimpleHTTPServer

Best of luck!
Rodrigo

**Comment by JasmaB** [comment]
Dear Rodrigo,

Thank you so much. I used Apache web server to resolve the issue.
